/** Gurugram area/sector options for dropdowns (keep in sync with BE/src/data/gurugramLocalities.ts). */

export const GURUGRAM_LOCALITIES: readonly string[] = [
  "Sector 14",
  "Sector 15",
  "Sector 17",
  "Sector 21",
  "Sector 22",
  "Sector 23",
  "Sector 28",
  "Sector 29",
  "Sector 31",
  "Sector 38",
  "Sector 39",
  "Sector 40",
  "Sector 43",
  "Sector 44",
  "Sector 45",
  "Sector 46",
  "Sector 47",
  "Sector 48",
  "Sector 49",
  "Sector 50",
  "Sector 51",
  "Sector 52",
  "Sector 53",
  "Sector 54",
  "Sector 55",
  "Sector 56",
  "Sector 57",
  "Sector 62",
  "Sector 63",
  "Sector 65",
  "Sector 66",
  "Sector 67",
  "Sector 70",
  "Sector 71",
  "Sector 82",
  "Sector 83",
  "Sector 84",
  "Sector 86",
  "Sector 89",
  "Sector 90",
  "Sector 91",
  "Sector 92",
  "Sector 93",
  "Sector 95",
  "DLF Phase 1",
  "DLF Phase 2",
  "DLF Phase 3",
  "DLF Phase 4",
  "DLF Phase 5",
  "Golf Course Road",
  "Sohna Road",
  "Sikanderpur",
  "Udyog Vihar",
  "Palam Vihar",
  "South City 1",
  "South City 2",
  "Nirvana Country",
  "Malibu Town",
  "MG Road",
  "IFFCO Chowk",
  "HUDA City Centre",
  "New Gurgaon",
] as const;

export function matchLocality(value: string): string | null {
  const t = value.trim();
  if (!t) return null;
  const lower = t.toLowerCase();
  const exact = GURUGRAM_LOCALITIES.find((l) => l.toLowerCase() === lower);
  if (exact) return exact;
  return GURUGRAM_LOCALITIES.find((l) => lower.includes(l.toLowerCase()) || l.toLowerCase().includes(lower)) ?? null;
}
